server:
  port: 8080
  tomcat:
    threads:
      min-spare: 1
      max: 4
      accept-count: 100000
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  threads:
    virtual:
      enabled: false
  application:
    name: GeotoolsDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: postgres
    password: qwer@123
    driver-class-name: org.postgresql.Driver
logging:
  level:
    com.application.*: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
#  group-configs:
#    - group: "user"
#      paths-to-match: '/user/**'
#      packages-to-scan: 'com.nongda.controller'
#    - group: "manager"
#      paths-to-match: '/manager/**'
#      packages-to-scan: 'com.nongda.controller'
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: root
    password: 311412


file:
  path: d:\tmp