server:
  port: 8080
  tomcat:
    #protocol: org.apache.coyote.http11.Http11NioProtocol
    #use-direct-buffers: true
    threads:
      min-spare: 1
      max: 4
      accept-count: 100000
spring:
  servlet:
    multipart:
      enabled: false
      location: d:\upload
      max-file-size: 20GB
      max-request-size: 20GB
  threads:
    virtual:
      enabled: false
  application:
    name: GeotoolsDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: postgres
    password: qwer@123
    driver-class-name: org.postgresql.Driver
logging:
  level:
    com.application.*: debug


springdoc:
  swagger-ui.path: /swagger-ui.html
file:
  path: d:\tmp